// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3R68Vl0KnjEsa5bli90ARtSg6KM_Xe5w',
    appId: '1:936402750074:web:b73b04f2987cb2e08e09c3',
    messagingSenderId: '936402750074',
    projectId: 'cinemate-7f090',
    authDomain: 'cinemate-7f090.firebaseapp.com',
    storageBucket: 'cinemate-7f090.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_5hFq6tB2Oc68U5D5Nk1mOvyvnnXYpgg',
    appId: '1:936402750074:android:8c75f033a50e41828e09c3',
    messagingSenderId: '936402750074',
    projectId: 'cinemate-7f090',
    storageBucket: 'cinemate-7f090.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMJFv2nz95MinoDDHRfmPH9i_JiSgYG4M',
    appId: '1:936402750074:ios:6122e4386f026eac8e09c3',
    messagingSenderId: '936402750074',
    projectId: 'cinemate-7f090',
    storageBucket: 'cinemate-7f090.firebasestorage.app',
    iosBundleId: 'com.example.movieApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMJFv2nz95MinoDDHRfmPH9i_JiSgYG4M',
    appId: '1:936402750074:ios:6122e4386f026eac8e09c3',
    messagingSenderId: '936402750074',
    projectId: 'cinemate-7f090',
    storageBucket: 'cinemate-7f090.firebasestorage.app',
    iosBundleId: 'com.example.movieApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3R68Vl0KnjEsa5bli90ARtSg6KM_Xe5w',
    appId: '1:936402750074:web:28e38ef8151133cb8e09c3',
    messagingSenderId: '936402750074',
    projectId: 'cinemate-7f090',
    authDomain: 'cinemate-7f090.firebaseapp.com',
    storageBucket: 'cinemate-7f090.firebasestorage.app',
  );

}